"""Typed event classifications for Project NOIR event stream."""

from enum import Enum


class EventType(str, Enum):
    # Lifecycle & Training Flow
    TRAINING_STARTED = "TRAINING_STARTED"
    TRAINING_PAUSED = "TRAINING_PAUSED"
    TRAINING_RESUMED = "TRAINING_RESUMED"
    TRAINING_STOPPED = "TRAINING_STOPPED"

    EPOCH_STARTED = "EPOCH_STARTED"
    EPOCH_COMPLETED = "EPOCH_COMPLETED"

    BATCH_STARTED = "BATCH_STARTED"
    BATCH_COMPLETED = "BATCH_COMPLETED"

    # Forward & Numerical Learning Steps
    FORWARD_PASS_COMPLETED = "FORWARD_PASS_COMPLETED"
    LOSS_CALCULATED = "LOSS_CALCULATED"
    BACKPROP_COMPLETED = "BACKPROP_COMPLETED"
    WEIGHTS_UPDATED = "WEIGHTS_UPDATED"

    # Reinforcement Learning
    REWARD_RECEIVED = "REWARD_RECEIVED"
    EPISODE_COMPLETED = "EPISODE_COMPLETED"

    # Affective / Mind Engine
    EMOTION_UPDATED = "EMOTION_UPDATED"
    UNCERTAINTY_UPDATED = "UNCERTAINTY_UPDATED"
    SURPRISE_DETECTED = "SURPRISE_DETECTED"

    # Storage & Persistence
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    CHECKPOINT_LOADED = "CHECKPOINT_LOADED"
    EXPERIMENT_CREATED = "EXPERIMENT_CREATED"
    EXPERIMENT_BRANCH_CREATED = "EXPERIMENT_BRANCH_CREATED"

    # Strategist & Hypotheses
    STRATEGY_UPDATED = "STRATEGY_UPDATED"
    HYPOTHESIS_GENERATED = "HYPOTHESIS_GENERATED"
    KNOWLEDGE_INGESTED = "KNOWLEDGE_INGESTED"

    # Hardware & System Telemetry
    SYSTEM_METRICS_UPDATED = "SYSTEM_METRICS_UPDATED"

    # System Status & Errors
    ERROR_OCCURRED = "ERROR_OCCURRED"
    LOG_MESSAGE = "LOG_MESSAGE"
